export const locations = [
    { 
      type: "school",
      name: "AFUK - The Academy of Untamed creativity", 
      about: "The Artistline is a preparatory program aimed at those who want to work in the entertainment industry, with contemporary circus, events, music halls, physical and visual theatre, or as a circus teacher. It is a good starting point from which to apply for admission to Vocational and Higher Education Circus Schools, work as a circus teacher or start your own company. About 50 students are on the Circus Programme.",
      address: "Enghavevej 82B, 2450 Copenhagen SV", 
      phone: "+45 32 54 20 95",
      email: "afuk@afuk.dk",
      website: "www.afuk.dk", 
      instagram: "www.instagram.com/artistlinien_afuk",
      facebook: "www.facebook.com/afukremisen",
      lat: 55.66230820175756, lon: 12.539834935878755,  },
    { 
      type: "school",
      name: "Gøglerskolen (FGU Århus)",
      about: "Preparatory education - the education lasts up to 2 years and is for you under 25 years of age who have not completed a youth education or are not in a full-time job.",
      address: "Olof Palmes Allé 39, 8200 Aarhus N",
      phone: "+45 87 40 86 00",
      email: "ab@fguaarhus.dk",
      website: "www.fguaarhus.dk/musisk-og-kunstnerisk-produktion", 
      instagram: "www.instagram.com/fgu.aarhus",
      facebook: "www.m.facebook.com/FGUmidtby",
      lat: 56.18928838143087, lon: 10.182195269797058,  },

    { 
        type: "school",
        name: "Musik og Teaterhøjskolen", 
        about: "You choose whether you want to work with Theatre or Contemporary Circus when you arrive at our school. You have some joint classes on these lines, and you experience and co-create the magic of the stage at the Theatre and Contemporary Circus lines. The two lines work with the stage expression, impression, and imprint, which are captured through different processes and productions – on the individual line separately and together",
        address: "Herrestedgade 6-8, 6520 Toftlund",
        phone: "+ 45 74 83 01 04",
        email: "kontor@musikogteater.dk",
        website: "www.musikogteater.dk/scenekunst", 
        instagram: "www.instagram.com/musikogteaterhoejskolen",
        facebook: "www.facebook.com/musikogteater.dk",
        lat: 55.19151330817705, lon: 9.065917498602422,  },
      {
        type: "company",
        name: "Glimt",
        about: "GLiMT is a professional performing arts company established in 2002 by Camila Sarrazin and Lars Lindegaard Gregersen. GLiMT combines contemporary circus, dance and physical theatre in order to create new and challenging performances that raise important questions about our society and the time we live in.",
        address: "c/o Foreningshuset Sundholm, Sundholmsvej 8, 2300 KBH S",
        phone: "+45 42 63 66 86",
        email: "info@glimt.info",
        website: "www.glimt.info/da",
        instagram: "www.instagram.com/glimt.info",
        facebook: "www.facebook.com/glimt.info",
        lat: 55.661289604180695, lon: 12.5968790697805,  
      },

      {
        type: "company",
        name: "Borderline Circus",
        about: "Borderline Circus is an artistic collective consisting of 3 funky artists with a lot of jazzy ideas and skills to impress. We may have high thoughts about ourselves, but we are ready to prove that we are right",
        address: "Borrelyngen 3, 2770 Kastrup",
        phone: "+45 61 66 87 94",
        email: "lalla@borderlinecircus.com",
        facebook: "www.facebook.com/BorderlineCircus",
        lat: 55.636173821145384, lon: 12.608307112106791,  
      },

      {
        type: "company",
        name: "Cikaros", 
        website: "https://cikaros.dk/",
        email: "cikaros@gmail.com",
        address: "Dagmarsgade 41, 4. tv, 2200 København N", 
        phone: "",  
        lat: 55.69885739597575, lon: 12.545222540945232,  
      },

      {
        type: "company",
        name: "Teater Kimone", 
        website: "http://kimone.dk/",
        facebook: "https://www.facebook.com/TeaterKimone/",
        email: "info@kimone.dk",
        address: "Jesper Brochmands Gade 4, 2200 København", 
        phone: "",  
        lat: 55.68861093552779, lon: 12.547068083271975,  
      },


      {
        type: "company",
        name: "Rapid Eye", 
        website: "http://www.rapideye.dk/",
        facebook: "https://www.facebook.com/RapidEyeContemporaryCircus",
        email: "info@rapideye.dk",
        address: "Otto Busses Vej 5A, 2450 København SV", 
        phone: "",  
        lat: 55.65969229060026, lon: 12.54942552745344,  
      },

      {
        type: "company",
        name: "TinCanCompany", 
        website: "tincancompany.dk",
        instagram: "https://www.instagram.com/tincancompany/",
        email: "info@tincancompany.dk",
        address: "Finlandkaj 6, 5000 Odense C", 
        phone: "",
        lat: 55.40830551005386, lon: 10.379748540936205,  
      },
      {
        type: "company",
        name: "X-act", 
        website: "kittjohnson.dk",
        instagram: "https://www.instagram.com/kittjohnsonxact/",
        facebook: "https://www.facebook.com/kittjohnsonxact",
        email: "x-act@kittjohnson.dk",
        address: "Struenseegade 15A, 3.th. 2200 København N", 
        phone: "",
        lat: 55.687098940204606, lon: 12.549599812108411,  
      },
      {
        type: "company",
        name: "Sputnik & Wild Wonders", 
        website: "http://www.sputnikandwildwonders.com/",
        instagram: "https://www.instagram.com/sputnikandwildwonders/",
        facebook: "https://www.facebook.com/sputnikandwildwonders/",
        email: "",
        address: "Egegade 18, 3 th. 2200 KBH N", 
        phone: "",
        lat: 55.690899512894866, lon: 12.558613898617903,  
      },
      {
        type: "company",
        name: "Sparrow Dance", website: "http://www.sparrowdance.dk/", 
        address: "Dansehallerne, H.C. Andersens Boulevard 25, 3. sal, DK-1553 København V", phone: "",
        lat: 55.674394029359206, lon: 12.571465254440337,  
      },
      
  ];
