export const locations = [
    { 
      type: "school",
      name: "AFUK - The Academy of Untamed creativity", 
      about: "The Artistline is a preparatory program aimed at those who want to work in the entertainment industry, with contemporary circus, events, music halls, physical and visual theatre, or as a circus teacher. It is a good starting point from which to apply for admission to Vocational and Higher Education Circus Schools, work as a circus teacher or start your own company. About 50 students are on the Circus Programme.",
      address: "Enghavevej 82B, 2450 Copenhagen SV", 
      phone: "+45 32 54 20 95",
      email: "afuk@afuk.dk",
      website: "https://afuk.dk", 
      instagram: "artistlinien_afuk",
      facebook: "afukremisen",
      lat: 55.66230820175756, lon: 12.539834935878755,  },
    { 
      type: "school",
      name: "Gøglerskolen (FGU Århus)",
      about: "Preparatory education - the education lasts up to 2 years and is for you under 25 years of age who have not completed a youth education or are not in a full-time job.",
      address: "Olof Palmes Allé 39, 8200 Aarhus N",
      phone: "+45 87 40 86 00",
      email: "ab@fguaarhus.dk",
      website: "https://fguaarhus.dk/musisk-og-kunstnerisk-produktion", 
      instagram: "fgu.aarhus",
      facebook: "FGUmidtby",
      lat: 56.18928838143087, lon: 10.182195269797058,  },

    { 
        type: "school",
        name: "Musik og Teaterhøjskolen", 
        about: "You choose whether you want to work with Theatre or Contemporary Circus when you arrive at our school. You have some joint classes on these lines, and you experience and co-create the magic of the stage at the Theatre and Contemporary Circus lines. The two lines work with the stage expression, impression, and imprint, which are captured through different processes and productions – on the individual line separately and together",
        address: "Herrestedgade 6-8, 6520 Toftlund",
        phone: "+ 45 74 83 01 04",
        email: "kontor@musikogteater.dk",
        website: "https://musikogteater.dk/scenekunst", 
        instagram: "musikogteaterhoejskolen",
        facebook: "musikogteater.dk",
        lat: 55.19151330817705, lon: 9.065917498602422,  
    },
      {
        type: "company",
        name: "Glimt",
        about: "GLiMT is a professional performing arts company established in 2002 by Camila Sarrazin and Lars Lindegaard Gregersen. GLiMT combines contemporary circus, dance and physical theatre in order to create new and challenging performances that raise important questions about our society and the time we live in.",
        address: "c/o Foreningshuset Sundholm, Sundholmsvej 8, 2300 KBH S",
        phone: "+45 42 63 66 86",
        email: "info@glimt.info",
        website: "https://glimt.info/da",
        instagram: "glimt.info",
        facebook: "glimt.info",
        lat: 55.661289604180695, lon: 12.5968790697805,  
      },

      {
        type: "company",
        name: "Borderline Circus",
        address: "Borrelyngen 3, 2770 Kastrup",
        phone: "+45 61 66 87 94",
        email: "lalla@borderlinecircus.com",
        facebook: "BorderlineCircus",
      },
     {
        type: "company",
        name: "The Amazing Other",
        about: "Playing, creating and performing, learning as much as we can, both circus, body moving, stage presence and stage combat, together we are the performing duo The Amazing Other.Lalla la Cour and Eivind Øverland is who we are and trapeze of all kinds is what we do: Duo, solo, static and swinging.",
        address: "",
        phone: "+45 61 66 87 94",
        email: "lalla@borderlinecircus.com",
        website: "https://theamazingother.simplesite.com",
        instagram: "the.amazing.other",
        facebook: "BorderlineCircus",
     },
    
      {
        type: "company",
        name: "Cikaros",
        about: "Cikaros is a collective with 3 circus artists that works to strengthen Danish new circus and put Danish circus art on the world map. Since its formation in 2005, Cikaros has produced and toured with new circus performances throughout Denmark and in Sweden, Norway, the Netherlands, France, Spain, Croatia, Russia, Egypt and Oman.",
        address: "Dagmarsgade 41, 4. tv, 2200 København N",
        phone: "+45 29 82 69 60",  
        email: "cikaros@gmail.com",
        website: "https://cikaros.dk",
        facebook: "profile.php?id=100039202342357",
        lat: 55.69885739597575, lon: 12.545222540945232,  
      },

      {
        type: "company",
        name: "Teater Kimone", 
        about: "Welcome to Theater Kimone's Intergalactic Universe! We are a young theater company that with roots in new circuses makes playful circus theater for children and young people. Since we are human, what we do is often also about human beings, and all the beautiful, fun and difficult things about being human.",
        address: "Jesper Brochmands Gade 4, 2200 København",
        phone: "+45 21 29 24 60", 
        email: "info@kimone.dk",
        website: "https://kimone.dk",
        facebook: "TeaterKimone",
        lat: 55.68861093552779, lon: 12.547068083271975,  
      },

      {
        type: "company",
        name: "Rapid Eye", 
        about: "Rapid Eye was founded in 2010 and has since managed to establish itself with a unique profile in modern performing arts. The company creates performances in the borderland between new circus, dance and visual theater. The performances are characterized by a love for man and his wonder about the world, and explore the perception of reality in a playful way.",
        address: "Otto Busses Vej 5A, 2450 København SV",
        phone: "+45 22 31 72 63",
        email: "info@rapideye.dk",
        website: "https://rapideye.dk",
        facebook: "RapidEyeContemporaryCircus",
        instagram: "rapideyetheatre",
        lat: 55.65969229060026, lon: 12.54942552745344,  
      },

      {
        type: "company",
        name: "TinCanCompany",
        about: "TinCanCompany was founded by the Danish artists Rune Vadstrøm Andersen and Gry Lambertsen. For 14 years, they have built a razor-sharp stage timing and a distinctive aesthetic universe. With devilish violence, warmth of heart and humor, they climb Chinese poles, go on the slapline and manipulate everyday objects.",
        adress: "Finlandkaj 6, 5000 Odense C", 
        phone: " + 45 22 66 53 67",
        email: "info@tincancompany.dk",
        website: "https://tincancompany.dk",
        facebook: "tincancompany",
        instagram: "tincancompany",
        lat: 55.40830551005386, lon: 10.379748540936205,  
      },
      {
        type: "company",
        name: "Kitt Johnson X-act",
        about: "Kitt Johnson X-act is one of the longest existing, most productive dance companies in Denmark. Founded in 1992, the company has evolved into a dynamic cultural enterprise, staging its own productions, producing and curating site-specific performance festivals, touring intensively at home and abroad, and offering physical classes, workshops, lectures and arts consultancy services.",
        adress: "Struenseegade 15A, 3.th. 2200 København N",
        phone: "+ 45 29 91 87 13",
        email: "x-act@kittjohnson.dk",
        website: "https://kittjohnson.dk",
        facebook: "kittjohnsonxact",
        instagram: "kittjohnsonxact",
        lat: 55.687098940204606, lon: 12.549599812108411,  
      },
      {
        type: "company",
        name: "Sputnik & Wild Wonders",
        about: "Our base is contemporary circus, with inspiration from the old style smokey salons, but with new redefined twists and concepts. To our wild wonders we invite fabulous and equally multi talented guest artists. We create and taylor sight specific cabarets, cross-over art collaborations, and are also available with our slack rope, acrobatic and cyr wheel skills to join inspiring projects.",
        adress: "Egegade 18, 3 th, 2200 KBH N",
        phone: "+ 45 26 80 76 88",
        email: "sputnikandwildwonders@gmail.com",
        website: "https://sputnikandwildwonders.com",
        facebook: "sputnikandwildwonders",
        instagram: "sputnikandwildwonders",
        lat: 55.690899512894866, lon: 12.558613898617903,  
      },
      {
        type: "company",
        name: "Sparrow Dance",
        about: "Sparrow Dance is an aerial dance and cross disciplinary stage art association formed by Esther Wrobel. The motivation behind Sparrow Dance is to promote and explore vertical dance and other suspended dance techniques to further expand the versatility of the performing arts. It aims to expand the possibilities of dance and develop the use of architecture as an active player in influencing movement.  Sparrow Dance aspires to challenge and play with the spatial perceptions of both the audience and the performers and explore alternate ways of looking at the world.",
        adress: "(c/o) Dansehallerne, H.C. Andersens Boulevard 25, 3. sal, DK-1553 København V",
        phone: "+ 45 31 75 03 09",
        email: "sparrowdance.info@gmail.com",
        website: "https://sparrowdance.dk",
        facebook: "sparrowdance",
        instagram: "sparrowdance.dk",
        lat: 55.674394029359206, lon: 12.571465254440337,  
      },
    {
        type: "company",
        name: "Out Of Balanz",
        about: "Out of Balanz is an award-winning, international ensemble based in Copenhagen, recognized for their highly collaborative creative process and for producing original work and adaptations that are rich in spectacle and adventurous in form.",
        adress: "Tjørnegade 9, 2200 København N",
        phone: "+ 45 52 73 92 68",
        email: "outofbalanz@gmail.com",
        website: "https://outofbalanz.com",
        facebook: "outofbalanz",
        instagram: "outofbalanz",
      },
    {
        type: "company",
        name: "Offspring Production",
        about: "We want to nurture and increase the use of physical performing arts in Denmark and abroad. Coming from niches within moving, like circus and the dance style electric boogie, we are exploring ways of mixing styles and how we can incorporate more storytelling in nonverbal expression forms.",
        adress: "Va11a, Siljangade 3, 2300 København S",
        phone: "+ 45 20 30 21 95",
        email: "mail@offspringproduction.dk",
        website: "https://offspringproduction.dk",
        instagram: "offspringproduction",
      },
    {
        type: "company",
        name: "Vice Versa Circus",
        about: "Danish circus company by two static trapeze artists.",
        adress: "Trunderup Dongsvej 30, Kværndrup",
        phone: "+ 45 27 12 39 80",
        email: "triotriskela@gmail.com",
        facebook: "Viceversacircus",
        instagram: "viceversacircus",
      },
    {
        type: "company",
        name: "Volantes",
        about: "Volantes is a new-thinking concept in performing arts with a special focus on circus skills. Our concept is to reach out to people with live performances and shows that will make the individual go home with an extraordinary feeling of inspiration and passion.",
        adress: "Skjulhøj Allé 21, 2720 København",
        phone: " +45 30 35 29 54",
        email: "djvolantes@gmail.com",
        website: "https://volantes.dk",
        instagram: "volantescompany",
      },
    {
        type: "company",
        name: "Tanter",
        about: "Tanter consists of Karoline (a strong fast rope artist), Moa (a slackrope artist with taste of drama) and Elise (a freak-magnet specialised in swinging trapeze and contortion). Three wild women who want to change the world for the better.",
        adress: "Va11a, Siljangade 3, 2300 København S",
        phone: "+ 45 22 88 67 96",
        email: "tanter@tanter.dk",
        website: "https://tanter.dk",
        facebook: "tanterkompani",
        instagram: "tanterkompani",
      },
          {
        type: "company",
        name: "Right Way Down",
        about: "Experimenting with the absurdity of reality upturned, you are invited to see the world the right way down.",
        adress: "Finlandkaj 6, 5000 Odense C",
        phone: "+45 22 96 50 79",
        email: "rightwaydowncircus@gmail.com",
        website: "https://rightwaydown.com",
        facebook: "rightwaydown",
        instagram: "rightwaydowncircus",
      },
     {
        type: "company",
        name: "Kristján Ingimarsson Company",
        about: "KIC is an award winning, world-touring physical theatre company under the artistic direction of Kristján Ingimarsson, a critically acclaimed Denmark-based Icelandic performer and director. Characteristic of KIC’s productions is their almost limitless physical expression along with endless curiosity.",
        adress: "Færgegaardsvej 17 d, 4760 Vordingborg",
        phone: "+ 45 25 53 55 13",
        email: "info@kicompany.dk",
        website: "https://kicompany.dk",
        facebook: "kicompanydk",
        instagram: "kristjan_ingimarsson_company",
      },
        {
        type: "association",
        name: "Cirkus Panik",
        about: "Cirkus Panik is one of the few surviving old-fashioned clown families and circus blood flows in our veins. We have been touring around and abroad for more than 35 years, with both classic circus performances, circus schools and workshops as well as rental of unique cotton circus tents.",
        adress: "Skjulhøj Allé 21, 2720 Vanløse",
        phone: "+ 45 24 27 93 40",
        email: "cirkus@cirkuspanik.dk",
        website: "https://cirkuspanik.dk",
        facebook: "cirkuspanik",
        instagram: "cirkuspanik",
      },
        {
        type: "association",
        name: "Cirkus Tværs",
        about: "Cirkus Tværs is a fully equipped children's and youth circus based in Gellerup, Brabrand. We work with the circus as a pedagogical tool, and thereby help children and young people to develop competencies, both personal, social, practical and professional.",
        adress: "Gudrunsvej 78, 8220 Brabrand",
        phone: "+ 45 86 25 87 80",
        email: "cirkus@mail.dk",
        website: "https://cirkustvaers.dk",
        instagram: "cirkustvaers",
      },
        {
        type: "association",
        name: "Ørkenfortet",
        about: "Our training is based on the joy of movement in a non-competitive space, where community, trust and attention are a big part of the activities. Here we work with the individual child at their level within floor and air acrobatics.",
        adress: "Enghavevej 82B, 2450 København",
        phone: "+ 45 24 26 24 50",
        email: "fortet@afuk.dk",
        website: "https://afuk.dk/foreninger/hold/",
        instagram: "afuk.orkenfortet/",
      },
     {
        type: "association",
        name: "Cirkusrummet",
        about: "Training space for professionals and amateurs.",
        adress: "Frederiksø 2, bygning K, 5700 Svendborg",
        phone: "+ 45 27 12 39 80",
        email: "cirkusrummet@gmail.com",
        facebook: "cirkusrummet",
      },
          {
        type: "association",
        name: "Innercirq",
        about: "If you want to try your hand at circus disciplines such as: aerial acrobatics, trapeze, floor acrobatics, partner acrobatics, Innercirq offers new circus training for children, young people and adults at all levels, from beginners to professionals.",
        adress: "Enghavevej 82B, 2450 København",
        phone: "+ 45 20 72 06 60",
        email: "info@innercirq.dk",
        website: "https://innercirq.dk",
        instagram: "innercirq",
      },
          {
        type: "association",
        name: "PACE",
        about: "Trainingspace and masterclasses for professionals.",
        adress: "Enghavevej 82B, 2450 København",
        phone: "+ 45 26 45 81 41",
        email: "pacecph@gmail.com",
        website: "https://pacecph.dk",
        facebook: "pacecph",
      },
          {
        type: "association",
        name: "The Circus Playground",
        about: "The Circus Playground is an open space, where we explore movement, circus and acrobatics in an open creative community.",
        adress: "Finlandkaj 6, 5000 Odense C",
        email: "thecircusplayground@gmail.com",
        facebook: "circusplayground",
      },
          {
        type: "festival",
        name: "Waves Festival",
        about: "WAVES FESTIVAL is an international festival for new, original and experimental theatre and performing arts that takes place every second year in Vordingborg. Artists from around the world present the latest and most exciting trends in theater, dance, comedy and performance art.",
        adress: "Færgegårdsvej 15, 4760 Vordingborg",
        phone: "+45 55 34 01 19", 
        email: "teater@cantabile2.dk",
        website: "https://wavesfestival.dk",
        facebook: "TheWavesFestival",
        instagram: "wavesfestivalofficial",
      },
          {
        type: "festival",
        name: "Passage Festival",
        about: "Passage Festival is a living street theater festival that is constantly evolving and expanding, not least in relation to what is going on around us. Urban space, audiences and artists are equal focal points in street theater in the public space.",
        adress: "Helsingør Teater, Strandgade 72, 1. 3000 Helsingør",
        phone: "+45 53 86 08 11",
        email: "th@helsingor-teater.dk",
        website: "https://passagefestival.nu",
        facebook: "passagefestival",
        instagram: "passagefestival",
      },
          {
        type: "festival",
        name: "Bornholms International Street Theater Festival",
        about: "BigF presents every summer Danish and international street theater and new circus for locals and for the many summer tourists regardless of age and nationality. All for FREE. BigF was started in 2011 by the international street theater group, Dansk Rakkerpak in collaboration with Theater Society Bornholm.",
        adress: "Teaterstræde 2, 3700 Rønne",
        phone: "+45 51 50 52 95",
        email: "bornholmsgadeteater@gmail.com",
        website: "https://bigf.dk",
        facebook: "BigF.dk",
        instagram: "bornholms.gadeteaterfestival",
      },
          {
        type: "festival",
        name: "Danmarks Internationale Gadeteater festivaler",
        about: "DIG (Denmark's International Street Theater Festivals) has existed since 2013 and offers free performing arts of international distinction in the middle of the street scene. Our performances fall into genres such as new circus, acrobatics, juggling, street parade, puppet theater, comedy and much more. We visit 10 Danish summer towns and present approx. 200 performances free of charge for the audience - for the benefit of young and old.",
        adress: "Strandvejen 100, 3. sal. 2900 Hellerup",
        phone: "+45 40 98 71 43",
        email: "info@gadeteaterfestival.dk",
        website: "https://gadeteaterfestival.dk",
        facebook: "gadeteater",
        instagram: "gadeteater",
      },
      {
        type: "festival",
        name: "C!CAF - Copenhagen Circus Arts Festival",
        about: "Copenhagen Circus Arts Festival is a biennale that shows international high-quality new circus art. Performances that catch you where the boundaries between circus and art are erased. Where something new and unique is created!",
        adress: "Kitt Johnson X-act, Rubinsteinsvej 47, 2450 København SV",
        phone: "+45 29 91 87 13",
        email: "x-act@kittjohnson.dk",
        website: "https://ccaf.nu/en/about-ccaf/",
        facebook: "CopenhagenCircusArtsFestival",
        instagram: "copenhagencircusartsfestival",
      },
      {
        type: "festival",
        name: "Metropolis",
        about: "Metropolis is a meeting point for performance, art and the city – an art-based metropolitan laboratory for the performative, site-specific, international art. It is Københavns Internationale Teater (KIT) that is behind Metropolis as the latest of a large number of festivals and projects in Copenhagen created and initiated by KIT.",
        adress: "c/o Københavns Internationale Teater, Refshalevej 163A, 1, 1432 København",
        phone: "+45 33 15 15 64",
        email: "info@kit.dk",
        website: "https://metropolis.dk/en/about-metropolis",
        facebook: "metropoliskbh",
        instagram: "metropoliskbh",
      },
      {
        type: "festival",
        name: "Dynamo Circus Festival",
        about: "DYNAMO Circus Festival: four days of contemporary circus, music, talks, films, workshops and cultural togetherness.",
        adress: "Finlandkaj 6, 5000 Odense C",
        phone: "+ 45 26 52 49 77",
        email: "info@dynamoworkspace.dk",
        website: "https://dynamoworkspace.dk/festival",
        facebook: "dynamoworkspace",
        instagram: "dynamo_workspace",
      },
      {
        type: "festival",
        name: "Cirkus i Soldalen",
        about: "This festival will give access to ''new-circus'' productions from all over Europe, showing that circus is much more than glitter, clowns and elephants. The performers combine circus with a variety of other arts; such as theatre, dance and music, so there will be something for everyone’s taste.",
        adress: "Maegårdsvej 4, 3770 Allinge, Danmark",
        phone: "+45 71 62 74 60",
        email: "cirkus.i.soldalen@gmail.com",
        website: "https://cirkusisoldalen.com",
        facebook: "Cirkus.i.Soldalen",
      },
      {
        type: "residencyandstage",
        name: "Dynamo Workspace",
        about: "DYNAMO is a stage and a workspace for circus and performing arts located in the middle of Denmark at Odense city harbor.",
        adress: "Finlandkaj 6, 5000 Odense C",
        phone: "+ 45 26 52 49 77",
        email: "info@dynamoworkspace.dk",
        website: "https://dynamoworkspace.dk",
        facebook: "dynamoworkspace",
        instagram: "dynamo_workspace",
      },
      {
        type: "residencyandstage",
        name: "AFUK Scene",
        about: "AFUK Scene presents own productions, guest performances, co-productions and festivals, primarily within new circus, physical theater and cross-over.",
        adress: "Enghavevej 82B, 2450 København V",
        phone: "+45 29 77 29 98",
        email: "afuk@afuk.dk",
        website: "https://afuk.dk/scene",
        facebook: "https://afukremisen",
      },
     {
        type: "support",
        name: "Udviklingsplatformen",
        about: "The purpose of the development platform is to develop and upskill independent performing arts throughout Denmark.",
        adress: "Farvergade 27, opgang D, 3 sal, 1463 København",
        phone: "+45 29 91 04 34",
        email: "admin@udviklingsplatformen.dk",
        website: "https://udviklingsplatformen.dk",
        facebook: "udviklingsplatformen",
        instagram: "udviklingsplatformen",
      },
     {
        type: "support",
        name: "Performing Arts Platform",
        about: "Performing Arts Platform is Aarhus’ development and networking platform for the performing arts. The platform brings together, facilitates and frames a strong cluster of performing art actors in and around Aarhus. Through the sharing and the communication of resources, skills and knowledge we generate development and supporting initiatives in the performing arts community.",
        adress: "Valdemarsgade 1G, 1. tv, 8000 Aarhus",
        phone: "+45 50 87 32 40",
        email: "theplatform@theplatform.dk",
        website: "https://theplatform.dk/en/home",
        facebook: "performingartsplatform",
        instagram: "performingartsplatform",
      },
     {
        type: "support",
        name: "Prfrm - Production And Dissemination Of Performing Arts",
        about: "A production community that has come together to ensure small and medium-sized companies as well as performing artists in the free field the necessary production assistance, which we are noticing an increasing demand for.",
        adress: "Hothers Plads 25, 3. sal, 2200 København N",
        phone: "+45 61 69 93 14",
        email: "info@prfrm.dk",
        website: "https://prfrm.dk",
        facebook: "prfrm.dk",
      },
     /*{
        type:
        name: 
        about:
        adress: 
        phone:
        email:
        website:
        facebook:
        instagram:
        lat: , lon:,
      },*/
  ];
